app/assets/stylesheets/application.css

Overriding some of the default mds colors with nucleus colors.  Targeting `.mds` instead of `:root` for specificity.

Use nucleus colors

---

app/components/hurdlr/hurdlr_component.html.erb
app/components/list_trac/list_trac_component.html.erb
app/components/widget_panel/widget_panel_component.html.erb

Just some minor updates based on design changes:
- Removed the search, filter, and heading elements from the widget library modal.
- Removed "Hide details" menu item
- Renamed "Change settings" to "Modify settings"
https://moxiworks.atlassian.net/browse/OT-45

OT-45 - Update widgets per design changes

---

app/components/hurdlr/hurdlr_component.html.erb
app/components/list_trac/list_trac_component.html.erb
app/components/widget_panel/widget_panel_component.html.erb

- Implemented drag sorting (for mouse, touch, keyboard, and screen readers).
- Fixed a hurdlr divide-by-zero bug when the income is zero.
- Fixed hurdlr menu item exceptions now that there are only two menu items.
- Fixed a few a11y issues.
https://moxiworks.atlassian.net/browse/OT-45
- Verify that widgets rearrange correctly when dragging and dropping.  Using touch, the drag handle is the icon only; using a mouse, the entire header is the drag handle.
- Verify that widgets rearrange correctly when using the keyboard.  Press Enter or Space to pick up a widget, and then press Enter or Space to drop it.  Pressing Escape or Tab cancels reordering.
[OT-45]: https://moxiworks.atlassian.net/browse/OT-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OT-45 - Implement widget panel drag sorting, etc.

---

app/components/hurdlr/hurdlr_component.html.erb
app/components/hurdlr/hurdlr_component.rb
app/components/list_trac/list_trac_component.html.erb
app/components/list_trac/list_trac_component.rb

Updated widgets to support the admin preview functionality:
- Widgets can now be set to library mode (demo data, no menu) via a query param.
- The widget heading and logo can be changed in realtime via postmessage.
- The logo link is now removed in library mode.
Also, I do think we should factor out a lot of this repeated code at some point, but I'm going to keep kicking that can down the road a bit longer until designs/requirements feel more nailed down.
https://moxiworks.atlassian.net/browse/OT-50
https://www.figma.com/file/S5TevaRcPuPa6wJNZePI5K/Widgets?node-id=1954%3A126044&t=opnMGU01ZDdgTyQK-0
Admin form is coming along nicely btw.  A nucleus PR will probably be along soon...

Update widgets for admin preview functionality

---

app/assets/stylesheets/application.css
app/components/hurdlr/hurdlr_component.html.erb
app/components/hurdlr/hurdlr_component.rb
app/components/list_trac/list_trac_component.html.erb
app/components/list_trac/list_trac_component.rb
config/routes.rb

- Added a new settings route for components.
- Built the settings modal for ListTrac.  I didn't bother with the Hurdlr settings modal just yet because I'm skeptical that we'll get Hurdlr to update their API for the settings in our design.
- Updated the expanded modal for ListTrac to match the latest design.
- Made the widget headings use an instance variable since those will be configurable in the widget admin.
- Also fixed the intermittent issues with the ListTrac expanded modal not opening.  Instead of waiting an arbitrary amount of time for the modal element to be ready to open, I've added a mutation observer that waits to open the modal until the wrapper element's child tree changes (presumably when the modal elements settle into place).  I also applied this fix to the new settings …

OT-44 - Add list_trac settings modal

---

app/components/list_trac/list_trac_component.html.erb
config/initializers/secure_request.rb
ops/dev/.irbrc

Big oops on the last PR.  I made it so the inline list_trac widget is only shown if the current path is the default list_trac component path, but we also need to render the inline list_trac widget whenever the current path is the widget_panel widget.  So now the inline widget is simply the `else` fallback after checking to see that the current path is neither the list_trac expanded path nor the list_trac settings path.
I also did a `standardrb --fix` on some files that were recently added by someone else.
Verify the list_trac widget renders inside the widget panel.

Fix list_trac not rendering inside widget panel

---

app/assets/stylesheets/widget_panel/style.css
app/components/hurdlr/hurdlr_component.html.erb
app/components/list_trac/list_trac_component.html.erb
app/components/widget_panel/widget_panel_component.html.erb
app/components/widget_panel/widget_panel_component.rb
app/controllers/api/user_widgets_controller.rb
app/controllers/api/widgets_controller.rb
app/helpers/api/user_widgets_helper.rb
app/helpers/api/widgets_helper.rb
app/models/widget.rb
config/routes.rb
test/controllers/api/user_widgets_controller_test.rb
test/controllers/api/widgets_controller_test.rb

This implements:
- adding and removing widgets from a user's dashboard via the library modal,
- removing a widget via the widget action menu,
- reordering widgets,
- and the API endpoints for both UserWidgets and Widgets.
I will probably circle back at some point to see about adding loading spinners or _something_ when "My Widgets" is refreshing after making changes in the library modal.
I will do a PR in nucleus for some changes that go along with this (https://github.com/moxiworks/nucleus/pull/701).
https://moxiworks.atlassian.net/browse/OT-44
https://moxiworks.atlassian.net/browse/OT-45
Verify that widgets can be added/removed from the library.  Verify they can be removed from the "My Widgets" panel as well.  When all widgets are removed from "My Widgets", the empty state should be …

Implement adding, removing, and reordering user widgets

---

app/components/widget_panel/widget_panel_component.html.erb

This updates the Widget Library modal to wait until all network requests are complete before closing the modal.  Otherwise, when the modal closes, its iframe is also cleared, which would cause pending network requests to be cancelled.

Wait to close Widget Library until requests finish

---

app/controllers/component_controller.rb

The action caching was not taking query string parameters into account, which we are using heavily, in addition to route params.  The updates the `cache_path` to the entire URL.

Set cache path to entire url (with query params)

---

app/components/hurdlr/hurdlr_component.rb
config/vendor_api_data.example.yml

Per advice from @aroop, switching to a single `token` instead of `production_token` and `sandbox_token` since we can just swap out different `vendor_api_data` depending on the environment.

Switch to single token in vendor api data

---

app/components/widget_panel/widget_panel_component.html.erb
app/components/widget_panel/widget_panel_component.rb
app/models/widget.rb

We use a `Object.const_get()` call to find the view component class for a widget.  Previously, this was in the view, which meant that if you added the `tips` widget to a user's widget panel, for example, and then switched to a branch that did not have that component, you would get an "Uninitialized constant" error.
This PR:
- Moves the `Object.const_get()` call to a `Widget.view_component` instance method that falls back to `nil`
- Filters the widget panel's `@active_widgets` to only show widgets that have a `view_component` to render

Handle missing view component files

---

app/components/hurdlr/hurdlr_component.html.erb
app/components/hurdlr/hurdlr_component.rb

- Provided fallback `@data` values inside the inline JavaScript.  Otherwise, if the API responds with an error and no good data, we would end up with lines like `{ label: 'Income', key: 'revenue', value:  }` (resulting in syntax errors in the browser console).
- Updated the hurdlr `user_vitals` API call to use the MLS ID from the user session instead of our test ID.  We may still use the test ID for some environments, depending on how hurdlr responds to Drew's latest email regarding test data.
- Changed the logic for the hurdlr API URL so that we use their production URL for both production and UAT; otherwise, we use their sandbox URL.  Ajay already configured the token this same way in the AWS Secrets Manager.

Hurdlr fixes

---

app/controllers/api/user_widgets_controller.rb
app/controllers/component_controller.rb

This removes action caching from the component controller.  There are just too many things that can change.
I also made it so that it should be impossible to create multiple `UserWidget` records for the same `widget_id` and `user_uuid`.
https://moxiworks.atlassian.net/browse/OT-121
https://moxiworks.atlassian.net/browse/OT-122
Verify that adding/removing widgets via the Widget Library takes effect immediately.
Verify that (de)activating widgets takes effect immediately (or at least after reloading the page).

OT-121 && OT-122 - Remove action caching from components; Prevent duplicate user widgets

---

app/components/hurdlr/hurdlr_component.html.erb
app/components/list_trac/list_trac_component.html.erb
app/components/tips/tips_component.html.erb

For some reason `url_for(@widget.logo)` sometimes returns an outdated URL.  I already had a `Widget.logo_url` method that uses `Rails.application.routes.url_helpers.rails_representation_url(logo, only_path: true)` instead, which seems to be more reliable.
https://moxiworks.atlassian.net/browse/OT-129

OT-129 - Use Widget.logo_url

---

app/assets/config/manifest.js
app/components/hurdlr/hurdlr_component.html.erb
app/components/list_trac/list_trac_component.html.erb
app/components/tips/tips_component.html.erb
app/components/widget_panel/widget_panel_component.html.erb

This replaces some `<link>` and `<img>` tags with rails asset helpers in order to use the correct files from the assets pipeline.
I also slipped in a fix for this text wrapping issue that Alex found in testing.

Fix widget assets by using rails helpers

---

app/controllers/application_controller.rb

This fixes the current user_uuid always being the same id.  😦 We originally were passing the user_uuid as a param, but we eventually switched to passing the session_id so we could also verify they were logged in.  JP forgot to update it to use the data from the auth service, and I somehow never caught it until now.
https://moxiworks.atlassian.net/browse/OT-134

OT-134 - Fix retrieving user_uuid from session_id

---

app/components/list_trac/list_trac_component.rb

☢️ This disables SSL verification for the ListTrac API endpoints, which are having cert issues.

Skip SSL verification for ListTrac API

---

app/components/tips/tips_component.html.erb

This adds a `max-width` to the CTA button so that the truncation works correctly.
https://moxiworks.atlassian.net/browse/OT-139

OT-139 - Fix CTA button overflow

---

app/controllers/api/widgets_controller.rb
db/migrate/20230328134804_rename_updated_by_uuid_column.rb
db/schema.rb

This updates the widget model to have an `updated_by` value instead of `updated_by_uuid`.  This is only used to show the name of the user that last updated the widget.  Since the widget-factory might eventually be integrated into other applications, just storing the name instead of some proprietary uuid feels more future-proof.
https://moxiworks.atlassian.net/browse/OT-138
As long as https://github.com/moxiworks/nucleus/pull/776 is also deployed, a name should appear under Last Updated on the widget admin form (after performing a save).

OT-138 - Add Widget.updated_by (and remove updated_by_uuid)

---

app/components/tips/tips_component.html.erb

This change makes the tip CTA button open the URL in a new tab.
_Not yet created_

Open CTA URL in new tab

---

app/components/widget_panel/widget_panel_component.html.erb

This changes the "Add" button's label to "Add Widget" so its context is clear even when it is far away from the "My Widgets" heading.
https://moxiworks.atlassian.net/browse/OT-146

OT-146 - Change "Add" button to "Add Widget"

---

Gemfile
Gemfile.lock
test/controllers/api/jwt_controller_test.rb
test/controllers/api/user_widgets_controller_test.rb
test/controllers/api/widgets_controller_test.rb
test/fixtures/widgets.yml
test/models/widget_test.rb
test/test_helper.rb

This adds 27 new assertions across 9 new test runs for the API controllers.  The `user_widgets_controller` tests required stubbing some JWT requests (using WebMock) since that controller relies on the user's UUID in the session.
I also fixed one of the widget fixtures that had an invalid value for `status`, which then required updating one of the `widget` model tests.
https://moxiworks.atlassian.net/browse/OT-148

OT-148 - API Controller Tests

---

app/components/hurdlr/hurdlr_component.html.erb
app/components/hurdlr/hurdlr_component.rb
app/components/list_trac/list_trac_component.html.erb
app/components/list_trac/list_trac_component.rb

- Added a 10-second timeout to all third-party API requests
- Added a new error message in the UI that is shown when `@error_with_api` is `true`
- Refactored the exception handling in the hurdlr and list_trac components
- Updated the hurdlr component to `console.error` any errors from the backend.  The list_trac component already did this, but I updated it to ensure that single quotes are escaped so the JavaScript doesn't break if the error message contains a single quote.
https://moxiworks.atlassian.net/browse/OT-150

OT-150 - Add handling/timeouts for third-party API requests, as well as a new message in the UI

---

test/components/hurdlr/hurdlr_component_test.rb
test/components/list_trac/list_trac_component_test.rb

Adding additional tests to the component test files for the hurdlr and list_trac components.  These tests verify that the error message in the UI is updated when `@error_with_api` is true.

OT-150 - Add components tests for @error_with_api

---

Gemfile
Gemfile.lock
apdev.yml
app/controllers/api/jwt_controller.rb
app/controllers/application_controller.rb
app/models/resource/auth.rb
app/models/session.rb
app/models/user.rb
app/models/widget.rb
app/sidekiq/event_logger_job.rb
config/application.rb
config/environments/dev_integration.rb
config/environments/development.rb
config/environments/production.rb
config/environments/qa.rb
config/environments/staging.rb
config/environments/test.rb
config/environments/uat.rb
config/initializers/sidekiq.rb
config/initializers/wms_svc_consumer.rb
config/redis.yml
config/routes.rb
test/controllers/api/jwt_controller_test.rb
test/test_helper.rb

- Modified the environment configs to set `config.base_service` like nucleus and other apps.  The `config.service_url` is then set in `application.config`.
- Added sidekiq:
- Added the sidekiq gem.  I did not use the enterprise gem because I don't think we'll need periodic jobs.
- Created the necessary initializer.
- Added a `widget-factory_sidekiq` service to `apdev.yml`.
- Added the route for the web UI.
- Created `redis.yml` (mostly copied from nucleus).  I created a ticket for ops to add the various environment instances.
- Added `config.active_job.queue_adapter = :sidekiq` to the application config.
- Created an initializer for `wms_svc_consumer` to set the service URLs (e.g. for the event service).
- Created an `EventLoggerJob`.  The actual event service logging part is still a work …

OT-152 - Add sidekiq and EventLoggerJob

---

app/components/hurdlr/hurdlr_component.html.erb
app/components/hurdlr/hurdlr_component.rb
app/components/list_trac/list_trac_component.html.erb
app/components/list_trac/list_trac_component.rb
app/components/tips/tips_component.html.erb
app/components/widget_panel/widget_panel_component.html.erb
app/components/widget_panel/widget_panel_component.rb
app/controllers/api/user_widgets_controller.rb
app/models/widget.rb
config/routes.rb
db/migrate/20230419155013_add_removed_to_user_widgets.rb
db/schema.rb
test/controllers/api/user_widgets_controller_test.rb
test/controllers/api/widgets_controller_test.rb
test/fixtures/user_widgets.yml
test/fixtures/widgets.yml

This changes the purpose and behavior of the `UserWidget` model.
Before, a user would start with no widgets.  They would add each widget, creating `UserWidget` records, which could also be reordered.  Removing a widget from their dashboard meant destroying the `UserWidget` records.
The problem with that is that there are thousands of users, and we want all users to start with all widgets by default.
With this PR, widgets are now shown by default unless explicitly removed by the user.  When they remove a widget from their dashboard, a `UserWidget` record is created/updated with the `removed` column set to `true`.  If the user reorders the widgets, then a `UserWidget` record is created/updated for each widget with the appropriate `row_order` value.  The `UserWidget` records are never …

OT-158 - Show widgets by default until user explicitly removes them

---

app/components/widget_panel/widget_panel_component.rb

This fixes an issue with the `where` and `or` chaining I was using to try to get active widgets that had not been removed by the user.  The user would be shown a deactivated widget if they had previously removed and then restored the widget to their dashboard.
I've instead subtracted the removed widget IDs from an array of active widget IDs and used that array in a single `where` clause, so it's much simpler and works perfectly now.
https://moxiworks.atlassian.net/browse/OT-161
Remove a widget from a user's dashboard and then add it back.  Deactivate that widget from the admin page.  The widget should not appear on the user's dashboard.

OT-161 - Fix active widget filtering

---

app/components/hurdlr/hurdlr_component.rb
app/components/list_trac/list_trac_component.rb

If there is an error from a partner API, _and_ logging of that error fails for some reason (e.g. because the EventLoggerJob does not work in QA right now), then the component should still render.
https://moxiworks.atlassian.net/browse/OT-161?focusedCommentId=707824 (@alexsheverenko's comment)

OT-161 - Do not raise exception if API error logging fails

---

app/components/list_trac/list_trac_component.rb

I was getting an intermittent "Token is not valid" error from the ListTrac API, particularly right after adding the widget from the library modal.  I realized that the component was requesting two tokens from ListTrac on every render (once to set `@token`, and once to request the `agent_listings`).  I updated the `agent_listings` method to use the previously set instance variable, and this seems to have fixed it.
This is not critical to the upcoming prod deployment (nor should it be a risky change if merged and deployed).
Remove and add the ListTrac widget via the library modal, and verify that there is no "Token is not valid" error logged to the console in dev tools.

Do not request list_trac token twice

---

app/components/inline_widget_component.html.erb
test/components/expanded_widget_component_test.rb
test/components/hurdlr/hurdlr_component_test.rb
test/components/inline_widget_component_test.rb
test/components/list_trac/list_trac_component_test.rb
test/components/tips/tips_component_test.rb

I've added component tests for the `inline_widget_component` and `expanded_widget_component`, and I've removed the redundant tests from the test files for `list_trac`, `hurdlr`, and `tips`.

Add test files for the new inline and expanded widget components

---

.standard.yml
Gemfile
app/assets/stylesheets/rismedia/style.css
app/components/application_component.rb
app/controllers/api/events_controller.rb
app/controllers/api/user_widgets_controller.rb
app/models/session.rb
config/application.rb
config/initializers/vendor_access.rb
ops/dev/.irbrc
test/controllers/api/user_widgets_controller_test.rb
test/controllers/api/widgets_controller_test.rb
test/test_helper.rb

I haven't been able to run all the lefthook pre-push checks for a while because standardrb kept crashing with a weird parser error.  I finally figured out that it was checking a lot of files that should have been ignored, but our `.standard.yml` was overriding the default ignores, so it was missing some of the defaults.
- Added a few more locations to the standardrb `ignores`
- Fixed all the linting errors.  I added an explicit ignore to one "offense" related to a variable name because I didn't want to risk breaking anything.

Fix standardrb crashes; Fix linting errors

---

app/assets/stylesheets/tips/style.css
app/components/tips/tips_component.html.erb

This adds line clamping to the tip shown in the `tips` widget, so users can clearly see that their tip is too long when previewing.  Although we have a reasonable character limit in place, real-world tips can still potentially end up with 8 or more lines if there are a lot of wide characters in use.
When the tip includes a CTA button, the widget only can fit 5 lines of text, but when there is no CTA button, it can show 7 lines.  Since there is no CSS selector for "previous sibling", I had to swap the order of the `mx-button` and `p` elements, so I could use the "next sibling" selector (`+`).  And in order to then display them in the same order as before, I changed their parent's `.flex-col` class to `.flex-col-reverse` (`flex-direction: column-reverse`). …

OT-184 - Fix tip overflow/scrolling

---

app/sidekiq/event_logger_job.rb

I just noticed a bunch of failed jobs in my local sidekiq dashboard, and it's because I wasn't parsing the `event_data` JSON in the sidekiq before trying to add the `component`, `board_uuid`, and `office_uuid` properties to that object.  Not sure how I missed this until now, but I'm glad I caught it.

Fix event_data in sidekiq job

---

app/assets/javascripts/expanded_widget_component.js
app/assets/javascripts/inline_widget_component.js
app/assets/javascripts/widget_panel_component_expanded.js
app/assets/stylesheets/application.css
config/initializers/mds_version.rb

- Set `overflow: hidden` on the body of the default layout to prevent a scrollbar in the My Widgets panel. [OT-207](https://moxiworks.atlassian.net/browse/OT-207)
- Updated MDS to v0.1.61, which fixes an issue with modals not opening when `isOpen` is set to `true` before the component has finished loading.  I was then able to remove the hacky mutation observers that were attempting to work around this issue. [OT-208](https://moxiworks.atlassian.net/browse/OT-208) https://github.com/moxiworks/mds/pull/240
- Fixed an issue with loading spinners appearing on all widgets while the Widget Library modal is opening.
- Updated the Widget Library to log events silently (without triggering a loading spinner over the My Widgets panel).
https://moxiworks.atlassian.net/browse/OT-207 …

OT-207 & OT-208 - Fix widget panel scrollbars and flaky modals

---

Gemfile
Gemfile.lock
config/initializers/datadog.rb

_Add support for Datadog for new Widget Factory service_
https://moxiworks.atlassian.net/browse/ENG-165830
- Ensure widget factory still works
- See if you get cool new stats in datadog (ActivePipe side)

Add support for datadog

---

README.md
app/components/external_widget/external_widget_component.html.erb
app/components/external_widget/external_widget_component.rb
app/controllers/component_controller.rb
app/helpers/components/external_widget_helper.rb
app/models/widget.rb
db/migrate/20230601203528_add_external_url_to_widgets.rb

This PR is for the initial implementation of the External Widget component that renders an external URL in an iframe.  It also replaces variables such as `{MLS_NUMBER}` in that external URL with values pertaining to the user.
As mentioned in the README, widgets are expected to have a unique `component` name, but all external widgets will use the same `external_widget` component for rendering, so external widgets will need to use something like `external_1`.  If I were starting this project over, I would avoid this "magic" prefix, but I think it's the least dangerous and least confusing way to patch this in now.
I'm targeting a new `ot-181-dev-portal` branch (based on `main`) with this PR since we will be releasing the RISMedia widget from `main` soon, and introducing a `release` or …

OT-202 - External Widget Component

---

app/components/inline_widget_component.html.erb

This updates the `inline_widget` component to not try to render the logo `<img>` if there is no logo attached to the widget.
https://moxiworks.atlassian.net/browse/OT-212
Remove the logo from a widget, and save the widget.  The widget should not show a broken image in the My Widgets panel.

OT-212 - Do not render <img> in widget footer if no logo is present

---

app/controllers/api/widgets_controller.rb
app/models/widget.rb
db/migrate/20230717154132_add_external_urls_to_widgets.rb
db/migrate/20230718132733_add_submitted_at_to_widgets.rb
db/migrate/20230718180237_add_submitted_by_uuid.rb
db/schema.rb
test/controllers/api/widgets_controller_test.rb
test/models/widget_test.rb

- Added migrations to add `external_preview_url`, `external_expanded_url`, `submitted_at`, and `submitted_by_uuid` columns to the `widgets` table.
- Added four new statuses to the `Widget` model:
- **unsubmitted** - We already had a "draft" status, so that's why this is called "unsubmitted".
- **submitted**
- **rejected**
- **review** - This will appear as "In Review" on the dev portal.
- Added ActiveRecord callbacks to automatically set the `submitted_at` date
- Added an ActiveRecord callback to automatically set the `component` value to `external_{id}` since it needs to be unique (see description here: https://github.com/moxiworks/widget-factory/pull/74)
- Added a `create` (POST) action to the `widgets_controller` and updated the permitted params accordingly
- Added test coverage for …

OT-203 - Update Widget model and API controller for dev portal submission

---

app/controllers/api/widgets_controller.rb
app/models/widget.rb
app/models/widget_submission_log.rb
db/migrate/20230719154857_create_widget_submission_logs.rb
db/migrate/20230719163802_add_submission_notes_to_widgets.rb
db/schema.rb
test/controllers/api/widgets_controller_test.rb
test/fixtures/widget_submission_logs.yml
test/fixtures/widgets.yml
test/models/widget_test.rb

- Added a new model `WidgetSubmissionLog` for implementing the History section of the widget submission form.  I decided to include the various external URLs in these logs just to be safe even though the design does not currently show those changes on the page.
- Added `submission_notes` to the `Widget` model that will be used by both the submitter and approver.
- Updated the API's `widgets#show` (GET) action to include the widget submission log entries in the JSON response.
- Updated the `Widget` model with various Active Record callbacks:
- Create a submission log entry when the widget's status changes (up until the widget has been approved).
- Create a submission log entry when a widget is created and submitted at the same time.
- Update the "submitted" log entry if the widget is …

OT-215 - Add WidgetSubmissionLogs and Widget.submission_notes

---

app/components/external_widget/external_widget_component.rb
app/helpers/components/external_widget_helper.rb
test/components/external_widget/external_widget_component_test.rb

- Added logic to use the `external_preview_url` instead of the `external_url` for the library modal (as well as the static preview in the nucleus admin)
- Added placeholder URL variable values for when the widget is in library mode or is being previewed in the dev portal (regardless of whether the iframe URL is the `external_url` or the `external_preview_url`).
- Added test coverage for the external widget component, which required adding `test_values` for the URL variables since the test environment in Rails does not have access to `session`.
https://moxiworks.atlassian.net/browse/OT-201

OT-201 - Use external_preview_url and/or demo values

---

app/components/external_widget/external_widget_component.rb

Just a quick fix to handle when `external_preview_url` is nil.
https://moxiworks.atlassian.net/browse/OT-201

OT-201 - Use external_url if no external_preview_url

---

app/components/external_widget/external_widget_component.html.erb
app/components/external_widget/external_widget_component.rb
app/controllers/api/widgets_controller.rb
app/models/widget.rb

This PR has a few changes that go along with https://github.com/moxiworks/nucleus/pull/820:
- Updated the `ExternalWidgetComponent` to render the `external_expanded_url`
- Added the `destroy` action to the widget API (for cancelling a submission from the dev portal)
- Added `submission_notes` to the API's permitted params
- Removed a line that previously cleared the `submission_notes` when an admin started reviewing a widget.  It's easier to just leave it on the widget record until the admin submits their approval or rejection.
https://moxiworks.atlassian.net/browse/OT-201
https://moxiworks.atlassian.net/browse/OT-203

OT-201 & OT-203 - Render external_expanded_url; API updates

---

app/controllers/api/widgets_controller.rb
app/models/widget.rb
config/routes.rb
db/migrate/20230906144146_add_parent_widget_id_to_widgets.rb
db/schema.rb
test/controllers/api/widgets_controller_test.rb
test/fixtures/widgets.yml
test/models/widget_test.rb

- Added `revise` and `merge` endpoints.  The `revise` endpoint creates a draft revision of a widget.  The `merge` endpoint then merges the revision back into the parent widget.
- Updated the `index` and `show` actions to include the revision and parent widget info
- Changed the `add_submission_log` callback to create a log when saving a draft (per design change).
- Changed `add_submission_log` to allow changing "review" status to "draft" per design changes.
- Changed the logic for when a widget can be deleted (approved edits can be deleted prior to merging), and moved this logic into a `can_destroy?` method.
- Updated tests
This PR is a prerequisite for https://github.com/moxiworks/nucleus/pull/827 in nucleus.
https://moxiworks.atlassian.net/browse/OT-203
- Edit an approved widget from …

Implement revising widget submissions

---

app/components/expanded_widget_component.html.erb

This updates the expanded widget modal to use the new `mx-modal` `unpadded` prop to remove the padding around the iframe.
https://moxiworks.atlassian.net/browse/OT-235

OT-235 - Do not pad iframe in expanded widget modal

---

app/assets/javascripts/expanded_widget_component.js
app/components/expanded_widget_component.html.erb

This removes the custom close button from the expanded widget modal.  The modal will now use the default slot content, which is an icon button in the latest modal component.

Remove expanded widget modal's custom close button

---

app/helpers/components/external_widget_helper.rb

The developer portal submission form already prepends external URLs with "https://" if no protocol is provided.  However, that only happens on save, so the previews might still try to use a URL without a protocol.
This PR ensures that any external URLs passed to the `external_widget` or `dev_widget_preview` components get the http(s) protocol.
https://moxiworks.atlassian.net/browse/OT-237
Create a new widget.  Enter something like `moxiworks.github.io/demo-widget/?mls-number={MLS_NUMBER}&nrds-number={NRDS_NUMBER}&full-name={FULL_NAME}` for one of the external URLs, and click Preview.  The preview should work.

OT-237 - Ensure external urls have http(s) protocol

---

app/assets/stylesheets/application.css
app/components/expanded_widget_component.html.erb

This removes the `width` and `height` attributes from the expanded widget modal logo, which act as minimums, and replaces them with `max-width` and `max-height`.  This should ensure that no logo overflows the modal footer.
https://moxiworks.atlassian.net/browse/OT-238
Choose a square logo on the widget submission form, and preview an external url.  The logo should be constrained to 105x48px.

OT-238 - Fix expanded widget logo dimensions

---

app/assets/javascripts/dev_widget_preview_component_library.js
app/components/dev_widget_preview/dev_widget_preview_component.html.erb
app/components/expanded_widget_component.html.erb
app/components/inline_widget_component.html.erb
app/views/component/_library_tile.html.erb

This adds truncation and wrapping to better handle long input text for the widget name and description.
For the description, this required dispatching a resize event to the nucleus preview iframe since the number of lines may vary. See https://github.com/moxiworks/nucleus/pull/839
https://moxiworks.atlassian.net/browse/OT-244

OT-244 - Handle long widget name or description
